### ISSUE TITLE
Target directory should be created

### ISSUE THREAD

**Issue by muety** [lgsvl/gym-lgsvl#1]
Right now, `random_agent.py` expects a directory `~/gym-lgsvl` to be existing to save the `tmp.png` to.
I put my gym in a different directory and consequently got a confusing error message until I changed the target directory.

`cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

I'd suggest that either the target directory should be created by the script or, even better, the image should be written to `/tmp`.

**Comment by daviduhm** [comment]
We've updated the code to use a relative path for saving a captured camera image: [commit](https://github.com/lgsvl/gym-lgsvl/commit/c3e422e7c9a76717abb86ba0dd523e356efd056e). It should work now when you put this repository in a different directory. Thanks for pointing it out!

**Comment by muety** [comment]
Cool, thanks for that fix. It works (although not tested on Windows).
An alternative would be to use [`tempfile`](https://docs.python.org/3.6/library/tempfile.html) and have [line 242](https://github.com/lgsvl/gym-lgsvl/commit/c3e422e7c9a76717abb86ba0dd523e356efd056e#diff-8f6dc57a5cb92db8eb01ef4d37a7651cR242) like this:

`filename = os.path.join(tempfile.gettempdir(), 'tmp.jpg')`

But I guess the issue can be closed anyway.

**Comment by daviduhm** [comment]
That's also a good option, but I would just keep it as long as it works (and it should work fine on Windows too). I'm actually not the original author of this repo (he's on a vacation at the moment), and my intention was to fix the issue without changing the functionality of the code and to keep the file path at the same location as before.
