### ISSUE TITLE
ModuleNotFoundError: No module named 'spinup'

### ISSUE THREAD

**Issue by muety** [lgsvl/gym-lgsvl#2]
The installation instruction don't mention to install `spinningup`. I just commented it out in `random_agent.py`, since it is only used for logging, to get the agent running. But I think either should it be mentioned in the instructions or replaced by some more "light weight" logging mechanism.

**Comment by daviduhm** [comment]
The documentation has been updated to install `spinningup`.

**Comment by roboserg** [comment]
The documentation does not mention anything about "spinningup" - https://www.svlsimulator.com/docs/third-party-integration/openai-gym/

Would you have a link to a proper documentation?
