### ISSUE TITLE
gym.error.UnregisteredEnv: No registered env with id: gym_lgsvl:lgsvl-v0

### ISSUE THREAD

**Issue by bobbyhaliwela** [lgsvl/gym-lgsvl#3]
When i run ./random_agent.py, it throws an error:

> gym.error.UnregisteredEnv: No registered env with id: gym_lgsvl:lgsvl-v0

Here are the traceback:

> Traceback (most recent call last):
>   File "/home/bob/anaconda3/lib/python3.5/site-packages/gym/envs/registration.py", line 143, in spec
>     return self.env_specs[id]
> KeyError: 'gym_lgsvl:lgsvl-v0'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./random_agent.py", line 6, in <module>
>     env = gym.make('gym_lgsvl:lgsvl-v0')
>   File "/home/bob/anaconda3/lib/python3.5/site-packages/gym/envs/registration.py", line 167, in make
>     return registry.make(id)
>   File "/home/bob/anaconda3/lib/python3.5/site-packages/gym/envs/registration.py", line 118, in make
>     spec = self.spec(id)
>   File "/home/bob/anaconda3/lib/python3.5/site-packages/gym/envs/registration.py", line 153, in spec
>     raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
> gym.error.UnregisteredEnv: No registered env with id: gym_lgsvl:lgsvl-v0
> 

Running this on Ubuntu 16.04.

**Comment by bobbyhaliwela** [comment]
Ah, turns out the cause was that the gym by default was installed into anaconda. Working now.

**Comment by ChunJyeBehBeh** [comment]
@bobbyhaliwela Hello, I have the same issue with you. May I know which gym version you install? How you solve it?

**Comment by hadiTab** [comment]
@ChunJyeBehBeh if you're getting the same error it generally means that either the gym-lgsvl package has not been installed, or that you have it installed for a different python than the one you are trying to run gym from (i.e. you likely have multiple python3 installations on your machine).
For example, Anaconda installs it's own python and you may have gym installed on that but gym-lgsvl installed on the system python.

**Comment by pgsudheesh** [comment]
I just have Anaconda installed in my system. I still have the error UnregisteredEnv: No registered env with id. What is the reason. How to solve it
