### ISSUE TITLE
Rewardfunction Lanefollowing Waypointtargeting

### ISSUE THREAD

**Issue by qsengshu** [lgsvl/gym-lgsvl#4]
Dear LGSVL Team,

Currently we are developing an lanefollowing reward function. It will reward our agent when it stays in its lane. For this we target the waypoints on the lanesegment "segment.TargetLocalPosition". We calculate the distance between the ego position and the nearest waypoint on the lane with regard to the agent in world coordinates. But we have a problem evaluating the correct waypoint which is beeing targeted in the UnitySimulator. Because the transform.position of the waypoints in the inspector of the UnitySimulator shows only LocalPosition. 

We are thinking about spawning an object at the position of the currentTarget for visualization in game scene. Is there a better and easier solution you would consider evaluating the correct target of the agent? 

Best Regards,
qsengshu

**Comment by hadiTab** [comment]
@qsengshu The ego vehicle doesn't target any of the waypoints by default, so I'm not sure what you mean by:

> we have a problem evaluating the correct waypoint which is beeing targeted in the UnitySimulator

Regardless, you can visualize all of the HD map waypoints in the editor, using the 'Map Tool Panel' as shown in [this tutorial](https://www.lgsvlsimulator.com/docs/map-annotation/).

If you have a specific 'target' waypoint that you know the coordinates of, you can visualize that waypoint using Gizmos. This would be much easier than placing an object at the position. For example you can draw a sphere at the known location as shown in [this example](https://docs.unity3d.com/ScriptReference/Gizmos.DrawSphere.html).

**Comment by qsengshu** [comment]
Thanks for your help @hadiTab. This solved the problem!
