### ISSUE TITLE
Bug: possible typo in collision callback registration

### ISSUE THREAD

**Issue by axelbr** [lgsvl/gym-lgsvl#8]
I did not try out anything, but i am pretty sure that the `on_collision` callback is not correctly registered due to a typo at [line 83](https://github.com/lgsvl/gym-lgsvl/blob/8a63f0fe00b6b52ed99c35ec47b9448a599aeb13/gym_lgsvl/envs/lgsvl_env.py#L83).

**Comment by bobbyhaliwela** [comment]
> I did not try out anything, but i am pretty sure that the `on_collision` callback is not correctly registered due to a typo at [line 83](https://github.com/lgsvl/gym-lgsvl/blob/8a63f0fe00b6b52ed99c35ec47b9448a599aeb13/gym_lgsvl/envs/lgsvl_env.py#L83).

Yes, you are correct. That, and the run function in line 84 is have no 'framerate' as argument. I changed these two lines in mine and everything works perfectly.
